### ISSUE TITLE
[Req] Transparent windows / frosted glas windows with comptom in terminal.

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantWM#1]
Not sure where to request this so i'l put it here.

**Comment by paperbenni** [comment]
Can you make this a little more specific? You want to have a partially transparent terminal background? Make the entire window transparent?

**Comment by NicTanghe** [comment]
Sorry for being so unspecific and posting in the nub question seems it should just be configured in urxvt? I'm switching to st now anyway so its fixed 4 me I'd still like a blurred or frosted background tho

**Comment by paperbenni** [comment]
It now ships with st by default with transparency set up. 
To enable blur type 
```iconf -i blur 1```
And reboot
