### ISSUE TITLE
create dwm patches 

### ISSUE THREAD

**Issue by luis-07** [instantOS/instantWM#111]
i love instantwm/instantos and this is because i want to have parts of instantwm in my dwm config could you create dwm patches?

**Comment by luis-07** [comment]
for example a patch that adds the nice look of the tag to dwm 
I dont want to turn dwm into instantwm I only want to have a few things from inatant wm in my dwm

**Comment by con-f-use** [comment]
Sorry, but patches for dwm to get selected functionality from instantWM to dwm would be by far too much work. Our instantWM has diverged too much from dwm and changes too much and much of instantWM functionality depends on certain programs to be installed and working. The maintenance and testing burden would just be too much. It's its own window manager and not compatible with dwm. If you want some of the functionality, implement it in dwm.
