### ISSUE TITLE
not working on zorinOS (ubuntu 20.04)

### ISSUE THREAD

**Issue by Aman9das** [instantOS/instantWM#119]
I ran the install commands on zorinOS and the option is there in the login screen

But when within instantWM, doing anything except clicking the workspaces is not working.. keyboard shortcuts and such..

maybe im doing something wrong.

startinstantos throws iconf command not found error in line 57

**Comment by paperbenni** [comment]
The GUI for instantos is modular, instantwm is just the window manager, if you want menus then you need to install them, otherwise nothing will happen if you try to open a menu. At the very least you should also install Instantmenu, that allows you to launch applications

**Comment by Aman9das** [comment]
Haha no benifit :(

I suppose its not ready for independent use yet, after the u get out of beta, add guide for us ubuntu people :)

**Comment by paperbenni** [comment]
Will do :)

**Comment by con-f-use** [comment]
For others reading this, if you need help, please the other means mentioned on the [support page](https://instantos.io/support). Github should be for development, rather than troubleshooting or tech-support.
