### ISSUE TITLE
No scalling of windows

### ISSUE THREAD

**Issue by HughJass** [instantOS/instantWM#12]
Great WM, I just tried it on Manjaro and I live it quite a bit. There's one thing (so far) that really stops me though. There seems to be no windows scalling at all. I'll be comparing with i3 which I use. For example Diablo2. This game has a hardcoded 800x600 resolution, so when you run it in windowed mode the window is pretty small. in i3 you cannot resize this window, however, if you unfloat it, it will become a fullscreen window (or half screen if there is another window etc). That way I can open diablo, unfloat it, open a terminal and resize the terminal to the size just a bit so that I have full screen 4:3 diablo 2 game. I instantWM this does not work. You cannot unfloat this game window. It also moves to the center of the screen (seemingly as a fallback from failed attempt of making the window tileable ?) so if you move your window somewhere and then keep on pressing super+shift+space the window will jump around from the original position to the center of the screen and back.

I don't know how i3 does it. Does it scale the window content on it's own ? I think having an option to resize the window in 2 ways would be really awesome:
1) to simply resize the window, making the application aware that the window is larger and making it draw more etc.
2) just scalling a window. Application still thinks the window is say 800x600 but the WM is scalling and positioning it freely.

EDIT: I just tried running diablo2 in fullscreen mode. On i3 the resolution changes to 800x600 which is fine, but it stays so after closing the game, making it hard to change back to your normal resolution (unless you have keybinds or can open terminal and blindly type in xrandr command). on InstamWM it surprisingly crashes whole xorg and goes back to tty

**Comment by paperbenni** [comment]
applications can request certain sizes from the wm. Usually this is done to prevent sizes that result in glitches in the UI. instantWM now has a way to force override this. you can now hold super+alt and resize the window with right click dragging the sides. That should let you resize anything to any size. To revert back to normal size simply super+right click drag the window
As for the xorg crash that should also now be fixed
