### ISSUE TITLE
`instantwm -v` does nothing

### ISSUE THREAD

**Issue by luphoria** [instantOS/instantWM#125]
Running `instantwm -v` prints the following:
`usage: instantwm [-v]`

when it should probably print the same as `instantwm --version`:
`instantwm-instantOS beta6-96-g3ba7b - Build Fri, Sep 16 2022, 15:10:09 +0200 on instantospc`

**Comment by paperbenni** [comment]
This has been implemented

**Comment by con-f-use** [comment]
Lower case `-v` should absolutely not print the version. It is commonly the flag to enhance verbosity. Capital `-V` is officially the short option for `--version`.

**Comment by luphoria** [comment]
> Lower case `-v` should absolutely not print the version. It is commonly the flag to increase verbosity. Capital `-V` is officially the short option for `--version`. If you ever introduce logging in instantWM this will cause confusion (wink ) and backward-compatibility issues.

This is a completely separate approach to the issue at hand. Mostly the issue is the `usage` print:
![image](https://user-images.githubusercontent.com/60309933/191605062-44a48914-c7f2-42ef-8335-e321df235257.png)
How this is approached is a design choice (and not my place to make one), but currently it prints `usage: instantwm [-v]` (lowercase). In my personal opinion and experience, lowercase v is generally version and not verbose; but, again, that's not my choice to make.

**Comment by con-f-use** [comment]
Here are some common tools, that use `-v` for verbosity and/or `-V` for version, you might recognize a few:

gcc, ssh, python, rustc, head, tail, less, more, rm, mv, cp, mkdir, wget, curl, netstat, htop, rg, ag, awk, man, lzma, bzip, locale, locate, fschk, mkfs, tar, telnet, gpg, openssl, udev, mount, zip, host, lvm, sudo, which, xauth, xz, youtube-dl, zfs

To just name a few. It's also POSIX recommendation.

**Comment by luphoria** [comment]
#126 fixes what I was referencing. And yeah, seems you're right about `-v` vs `-V` :zany_face:
