### ISSUE TITLE
Is it a requirement of InstantOS?

### ISSUE THREAD

**Issue by DakshMiglani** [instantOS/instantWM#14]
Hi,

I already use Arch and I do not want to switch, however I've looked at InstantOS and it seems InstantWM is pretty cool.

Is it exclusively made to run with other tools of instantOS or will it work with other distro's as well?

**Comment by skbolton** [comment]
@DakshMiglani did you figure this out? I am in the same boat as you.

**Comment by con-f-use** [comment]
You can install the packages form AUR, but instantWM is made to be used with other software, most notably the status bar, the menus and stuff that is started with the keyboard shortcuts.
