### ISSUE TITLE
NixOS testing beta2

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [instantOS/instantWM#15]
Is instantwm working on other distros that instantOS?

I see a lot of instantos specific code in the wm so I guess the answer might be not yet.

Anyway, here are the issues experienced during testing : 
 - instantautostart 
https://github.com/instantOS/instantWM/blob/f4142b65b0b259e05b365d027844ca551900ce02/instantwm.c#L2962
 - instantshutdown
https://github.com/instantOS/instantWM/blob/0997b563ffc68b6082dd8ba761b687f83a7ec9ff/config.def.h#L146 (this one could be configured though).

### Config
tested on **beta2**
configured with **xsession**, just running command instantwm.

--------

looking at journalctl, most issues comes from non-existing executables : 

Now regarding what I could do : 
 - I could switch the layouts, (with Super + t and Super + f).
 - I could switch to all the workspaces and select them all with Super + 0
 - Once configured, I could launch a terminal with Enter or Super + Enter

What I couldn't do:
 - Using most keybindings would crash the wm and get me back to DM.
 - The space key didn't work (no applications launched) even with rofi installed
 - Since instantmenu isn't installed, I couldn't open the instantmenu.

**Comment by paperbenni** [comment]
instantWM does depend on other packages for some features and that likely is not going to change. But you can install these on other distros as well by adding ```http://instantos.surge.sh/``` to your mirror list. Debian packages are also planned, but are at the back of the todo list. 
The rofi menu doesn't work because the configuration for it is contained in another package. 
The crashing is surprising though. I am not familiar with NixOS but if an additional feature is missing, it usually does nothing. Which hotkeys did crash the WM for you?

**Comment by SCOTT-HAMILTON** [comment]
In the process of packaging instantwm and mandatory instantos tools, I'm wondering what provides/what's for this file : 
https://github.com/instantOS/instantOS/blob/e8d563593b148dedbd92fa9ddd0b69cdbf9fd938/programs/appmenu#L2
`~/.config/instantos/israspi`?

**Comment by SCOTT-HAMILTON** [comment]
Couldn't find what package provides iconf https://github.com/instantOS/instantOS/blob/c7b75b0db48866557e82e5f47b5b89800a55c0e4/autostart.sh#L8

**Comment by SCOTT-HAMILTON** [comment]
Ok, so iconf is just a symlink to instantconf.

**Comment by con-f-use** [comment]
Hi, as your second Patreon, I'd very much like to request NixOS support ;-)
I can probably help given some time.

**Comment by SCOTT-HAMILTON** [comment]
Yes, they are over on my NUR repository https://github.com/SCOTT-HAMILTON/nur-packages-template/tree/instantos
branch instantos.

This is heavy WIP as you ca imagine.

**Comment by con-f-use** [comment]
I don't have incredibly much time on my hands, but I'd like to help. I'll have a look. Thanks.
Maybe we could make a group or something? **instaNtixOs** ftw! :grin:

**Comment by SCOTT-HAMILTON** [comment]
Sure, seems like a good idea.

**Comment by con-f-use** [comment]
@schachmat : https://discord.gg/Zw8E6p

**Comment by con-f-use** [comment]
Just for the record, this exists now: https://github.com/instantOS/nix
