### ISSUE TITLE
Glitching in top bar when moving mouse between 2 monitors quickly

### ISSUE THREAD

**Issue by RubenHetKonijn** [instantOS/instantWM#17]
When i move my mouse quickly between my 2 monitors, the top bar glitches a bit, 
FYI: i have a pentium g2020 and 4GB of ram and no dedicated gpu

**Comment by paperbenni** [comment]
What kind of glitches are happening?
I can't reproduce the issue with the current version of instantWM

**Comment by RubenHetKonijn** [comment]
Yea I can't seem to replicate it anymore after a reinstall.
