### ISSUE TITLE
Side panel feature request

### ISSUE THREAD

**Issue by OwczarekGit** [instantOS/instantWM#20]
I've seen @paperbenni streams recently and seeing you juggling the chat window around gave me an idea. I thought about "side panel" that works the same way as overlay so you can assign a window to it for example: messaging app, irc or stream chat as shown on the quick demo below(obviously it has to go to the side but you get the idea). I think it would be useful especially on single monitor setups where you want to use as much screen space as possible and from time to time peek on some chat.

![demo](https://user-images.githubusercontent.com/32412218/90293253-f0c8e080-de83-11ea-8b54-17479a9cc5f6.gif)

**Comment by paperbenni** [comment]
Guess I can close this now
