### ISSUE TITLE
Monocle layout fullscreen apps not changing properly

### ISSUE THREAD

**Issue by OwczarekGit** [instantOS/instantWM#22]
In monocle layout while watching fullscreen video either in proper player or browser(i think generally fullscreened programs cause this issue) cycling between windows(Super + J/K) changes focused window without swapping fullscreen program with facused window.

**Comment by con-f-use** [comment]
The question is, what would be the correct behavior? The thing I'd probably expect is leaving fullscreen and change active window.

**Comment by OwczarekGit** [comment]
Yea either that or making it behave the way that is the most expected by creating different behaviors depending on workspace layout, ex. in tiling layout it makes sense that the fullscreen mode gets disabled and other window gets focused, in monocle layout it basically feels like all windows are "maximized" so it makes sense to make them behave like they would on any mainstreem desktop environment(they just pop up on to of eachother without modifying one's fullscreen state) same in floating layout but respecting the floating rules. Just an idea, but i think that would make sense.
