### ISSUE TITLE
Feature Request: Installation option to go back

### ISSUE THREAD

**Issue by SirFrankieCrisp** [instantOS/instantWM#24]
Love the text installer! Only thing I think is missing would be a way to go back to the previous step of the. Also, when instead of confirming the settings before the installation finishes, you don't confirm them, it kicks you back to the beginning. It would be nice to be able to choose which step to modify, maybe even being able to click on a specific topic in the list and change only that.

Thanks for the hard work, beta 4 looks amazing!

**Comment by paperbenni** [comment]
This was added to https://github.com/instantOS/instantARCH in beta 6
