### ISSUE TITLE
Window past workspace 20

### ISSUE THREAD

**Issue by hen6003** [instantOS/instantWM#27]
it is possible to push a window past workspace 20 (onto 21), it's not possible for workspace 1 to 0.

**Comment by con-f-use** [comment]
I think 20 workspaces are enough. To my knowledge there is nothing <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>1-0</kbd> for workspaces over ten, i.e. nothing to move a window there quickly, other than <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>→</kbd>.

**Comment by paperbenni** [comment]
This was not the issue, he was on workspace 20 and was able to move a window to the adjacent workspace on the right which does not exist. It is fixed now though

**Comment by con-f-use** [comment]
Ah wow, I read "it isn't possible...". Sorry.

**Comment by hen6003** [comment]
> This was not the issue, he was on workspace 20 and was able to move a window to the adjacent workspace on the right which does not exist. It is fixed now though

cool
