### ISSUE TITLE
what to do next?

### ISSUE THREAD

**Issue by Konradrundfunk** [instantOS/instantWM#3]
Hi I have followed your instructions but what sould I do next how can I acces the WM? I have the newest Manjaro installed currently under gnome.

**Comment by paperbenni** [comment]
You'll need instantutils from http://instantos.surge.sh/ that'll get the basics working. 
But instantWM is meant to run under instantOS, support for other distros is experimental and will be focused on after the first stable release of instantOS. 
There will be a script that installs instantWM and all components needed for it on manjaro/arch in the future.

**Comment by Konradrundfunk** [comment]
Ah ok thank you very much thats prommising I think I'll wait.

**Comment by salifm** [comment]
@paperbenni 
Sorry for the off-topic, but I installed instantdotfiles from http://instantos.surge.sh and it messed my configurations. How to undo it? For example my .gitconfig was replaced by yours and I accidentally made git commit with your name and email.

**Comment by paperbenni** [comment]
I totally forgot that my name was in the git config, thanks for reminding me :)
you can undo the gitconfig change by doing these. 
```sh
git config --global user.name yourname
git config --global user.email yourname@mail.com
```
instantdotfiles contains the default dotfiles for instantos, it's not really ready for use outside of instantOS yet, but an alternative mode that allows for usage on top of existing setups will be added. 
Unfortunately there is as of now no way to revert to previous configurations, you will have to do that manually. Sorry for the inconvenience. 
I just added an archiving feature that updates any old files before overwriting them, a command to revert to previous configurations will be added as well. 
If you have instantsettings and instantconf installed as well you can disable the management of individual dotfiles in the dotfiles section of the control center, that's what I'd recommend for now.
