### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by genofire** [instantOS/instantWM#34]
Any plans to migrate to wayland?

This should use less ressources then X11 and make instantWM much faster ...
There is much work done in https://github.com/swaywm/wlroots  by the sway window manager (which want to be equal to i3-wm)

**Comment by con-f-use** [comment]
Fourth time this has been asked this week. Wayland seems to be very popular. Please see this answer: https://github.com/instantOS/instantOS/issues/73#issuecomment-699472347
