### ISSUE TITLE
Mouse control over tiling layouts

### ISSUE THREAD

**Issue by bob8677** [instantOS/instantWM#47]
First I just want to say I really appreciate this project and all the work that went into it. One problem I have is that I cannot move windows up or down the stack with only the mouse. This is most problematic when using a touchscreen device, but it would also but nice to have some control over the tiling layouts without touching the keyboard. If I try to drag the window titles to a side, I just end up dragging the corresponding window in floating mode. Dragging the window titles like they are browser tabs to change where they are in the layout would provide an option to adjust window order without the keyboard.

**Comment by con-f-use** [comment]
> Dragging the window titles like they are browser tabs to change where they are in the layout would provide an option to adjust window order without the keyboard.

That sounds interesting.

**Comment by paperbenni** [comment]
That's a really good idea. I added it to the todo

**Comment by bob8677** [comment]
#82
