### ISSUE TITLE
Feature Request | Help screen like in AwesomeWM

### ISSUE THREAD

**Issue by DrMagPie** [instantOS/instantWM#5]
Hi,

I know that AwesomeWM is also a fork of DWM. and it has wonderful [help menu](https://preview.redd.it/9y6vrdmnp4b41.png?width=1282&format=png&auto=webp&s=b394eebda763d555f71da42c184f14a74dc06303), which is really helpful to a new users, or with some stuff that is really used.

Im curious, would it be possible to add something similar to InstantWM.
This would make it a bit more beginner friendly, and would allow you to display some of default keybindings.

Best Wishes :)

**Comment by Aureau** [comment]
it's already there, Super + F1 is the keybinding to show it up

**Comment by DrMagPie** [comment]
hhhmmm I see.
Didn't notice it :)
Thats awesome! Thank you!
