### ISSUE TITLE
Edge case with window size, multiple monitors, and bar visibility.

### ISSUE THREAD

**Issue by XeroOl** [instantOS/instantWM#53]
Steps to reproduce:
1: Have two monitors, both set to the default stack layout.
2: Hide the bar (with `<Super>B`) on Monitor 1, and leave the bar visible on Monitor 2
3: Open some windows on Monitor 1 (with `<Super>+<Enter>` , for example)
4: Move a floating window between Monitor 1 & 2 by dragging it with left click + Super.
5: Observe the bottom of the screen.

Expected behavior:
None of the tiled windows resize when the floating window is moved between monitors.

Actual Behavior:
The tiled windows erroneously change their size.

Video: https://streamable.com/4uayze
(Streamable doesn't host videos indefinitely, so don't be surprised if the link expires.)

**Comment by bob8677** [comment]
I can reproduce this, not sure whats going on.

**Comment by paperbenni** [comment]
Holy cow it auto closes the issue. Didn't indend that, would be nice if someone confirms the issue is gone in the latest master

**Comment by XeroOl** [comment]
I can confirm that the issue is gone
