### ISSUE TITLE
Failing to build on Pop_OS (fatal error: X11/Xft/Xft.h: No such file or directory)

### ISSUE THREAD

**Issue by Ramiferous** [instantOS/instantWM#56]
```
 λ ~/Downloads/instantWM ./build.sh                                                                                                                                               2 ↵ master
instantwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wunused -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="instantOS 3f0bc - Build Mon, Dec 7 2020, 22:59:46 +1100 on pop-os" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lm
CC       = cc
VERSION  = instantOS 3f0bc - Build Mon, Dec 7 2020, 22:59:46 +1100 on pop-os
cp config.def.h config.h
cc -c -std=c99 -pedantic -Wall -Wunused -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\""instantOS 3f0bc - Build Mon, Dec  7 2020, 22:59:46 +1100 on pop-os"\" -DXINERAMA drw.c
drw.c:7:10: fatal error: X11/Xft/Xft.h: No such file or directory
    7 | #include <X11/Xft/Xft.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: drw.o] Error 1
instantwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wunused -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="instantOS 3f0bc - Build Mon, Dec 7 2020, 22:59:46 +1100 on pop-os" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lm
CC       = cc
VERSION  = instantOS 3f0bc - Build Mon, Dec 7 2020, 22:59:46 +1100 on pop-os
cc -c -std=c99 -pedantic -Wall -Wunused -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\""instantOS 3f0bc - Build Mon, Dec  7 2020, 22:59:46 +1100 on pop-os"\" -DXINERAMA drw.c
drw.c:7:10: fatal error: X11/Xft/Xft.h: No such file or directory
    7 | #include <X11/Xft/Xft.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: drw.o] Error 1
```

**Comment by paperbenni** [comment]
It says right there, you're missing xft headers. install those and you'll be fine

**Comment by con-f-use** [comment]
Btw. popOS or anything other than Archlinux based distributions are not really in scope here and the Discord / Telegram / Matrix / Reddit is a better place to ask about it and get it running on those.

**Comment by Ramiferous** [comment]
> 
> 
> It says right there, you're missing xft headers. install those and you'll be fine
> the package naming scheme afaik is libfoo-dev for headers which in your case is
> `sudo apt install libxft-dev`

Thank you, this is what I couldn't figure out. Cheers.


> 
> 
> Btw. popOS or anything other than Archlinux based distributions are not really in scope here currently and the [Discord / Telegram / Matrix / Reddit](https://instantos.io/support) is a better place to ask about it and get it running on those. This Github repo should primarily be focused on development of the main flavor rather than tech support and learning questions or questions regarding integration into other distros/architectures. See: [#57 (comment)](https://github.com/instantOS/instantWM/issues/57#issuecomment-739998829)

Fair enough. For what it's worth, I believe expanding on the OS compatibility of InstantWM will no doubt increase exposure to InstantOS. It's kind of why I want to install it on popOS, so I can get a feel for InstantWM as a daily driver (and on real hardware) before I choose to switch to InstantOS. 

Anyway, cheers, love the project.

**Comment by con-f-use** [comment]
Sure, but a lot of functionality will be wonky if it's not done well and that will accomplish the opposite and turn people off from instantOS.
