### ISSUE TITLE
Create a new release (beta5) to be able to package it into Fedora

### ISSUE THREAD

**Issue by X3MBoy** [instantOS/instantWM#57]
I'm not a proven packager, but I'm trying to build it in Fedora's Copr. But to be able to do that (with my little knowledge) I need a "release" artifact that I can refer to in my spec file.

**Comment by con-f-use** [comment]
Please discuss this on [Discord / Telegram / Matrix / Reddit](https://instantos.io/support). Currently, we are in beta and target Archlinux-based distributions only here. There are efforts with [Nix/NixOS](https://github.com/instantOS/instantNIX) (might "work" on Fedora) and [Ubuntu](https://github.com/instantOS/instantUBUNTU) (abandoned) and [ARM](https://github.com/instantOS/instantOS-arm), but not by the instantOS main developer and currently not in scope.

**Comment by paperbenni** [comment]
Packages on Arch are just regular compressed tar files, you can download compiled binaries at http://packages.instantos.io/
But you should also keep in mind that to have a good experience you also need some of the other instantOS components, the WM really is just a WM. Providing binary releases on github is actually a good idea but likely won't be a thing until things get more stable. In the long run you might compile on the target distro as it's not always guaranteed that libraries are in the same places on every distro. And as confuse said, this might be better suited to the community channels. feel free to join https://discord.io/instantos and discuss things there

**Comment by X3MBoy** [comment]
> Packages on Arch are just regular compressed tar files, you can download compiled binaries at http://packages.instantos.io/
> But you should also keep in mind that to have a good experience you also need some of the other instantOS components, the WM really is just a WM. Providing binary releases on github is actually a good idea but likely won't be a thing until things get more stable. In the long run you might compile on the target distro as it's not always guaranteed that libraries are in the same places on every distro. And as confuse said, this might be better suited to the community channels. feel free to join https://discord.io/instantos and discuss things there

Sorry I was unclear, I wasn't talking about "binaries" but to set a point where the new "release" start and the last one is considered stable. There was one set in https://github.com/instantOS/instantWM/releases for beta2. Basically what I was needing was an URL like https://github.com/instantOS/instantWM/archive/beta2.tar.gz but if it can't be, that's ok.

Also, it's ok that the WM is just a WM, I just want to package that, since I can't package the entire OS into a distribution.

I will try to join the community.

Thanks for the answers.

**Comment by con-f-use** [comment]
Yeah, we should synchronize the tags across all the repos, I agree. `instantOS/instantOS` is the authoritative repo when it comes to versioning.

**Comment by X3MBoy** [comment]
> Just to make sure, you do compile the fedora binary of instantos from source for your packaging effort, right?

Yes the idea is to compile de WM from source to create the Fedora RPMs
