### ISSUE TITLE
crashes when using xrandr to resize

### ISSUE THREAD

**Issue by mybigman** [instantOS/instantWM#6]
@paperbenni  I know that this project is really only supported under instantOS but this could help down the road if it becomes a window manager that supports other OSes.

I took it for a test run under fedora 32, everything compiled and installed without issues.

After launching iWM, opening a terminal and running ```xrandr -s 1920x1440``` it instantly crashed out of the WM and back to the shell prompt.

Note - In i3WM the same command works as expected.

#### edit
I just installed i0S in a VM opened the terminal and typed the same command and it complete hung the system.

#### xorg log
```
[  4120.756] (II) modeset(0): Allocate new frame buffer 1920x1440 stride
[  4121.018] (**) Option "fd" "21"
[  4121.018] (II) event0  - Power Button: device removed
[  4121.018] (**) Option "fd" "24"
[  4121.018] (II) event1  - Sleep Button: device removed
[  4121.018] (**) Option "fd" "25"
[  4121.018] (II) event5  - Video Bus: device removed
[  4121.018] (**) Option "fd" "26"
[  4121.018] (II) event6  - VirtualBox mouse integration: device removed
[  4121.018] (**) Option "fd" "27"
[  4121.018] (II) event4  - VirtualBox USB Tablet: device removed
[  4121.018] (**) Option "fd" "28"
[  4121.018] (II) event2  - AT Translated Set 2 keyboard: device removed
[  4121.018] (**) Option "fd" "29"
[  4121.018] (II) event3  - ImExPS/2 Generic Explorer Mouse: device removed
[  4121.019] (II) UnloadModule: "libinput"
[  4121.019] (II) systemd-logind: releasing fd for 13:67
[  4121.032] (II) UnloadModule: "libinput"
[  4121.032] (II) systemd-logind: releasing fd for 13:66
[  4121.038] (II) UnloadModule: "libinput"
[  4121.038] (II) systemd-logind: releasing fd for 13:68
[  4121.059] (II) UnloadModule: "libinput"
[  4121.059] (II) systemd-logind: releasing fd for 13:70
[  4121.073] (II) UnloadModule: "libinput"
[  4121.073] (II) systemd-logind: releasing fd for 13:69
[  4121.089] (II) UnloadModule: "libinput"
[  4121.089] (II) systemd-logind: releasing fd for 13:65
[  4121.097] (II) UnloadModule: "libinput"
[  4121.097] (II) systemd-logind: releasing fd for 13:64
[  4121.109] (II) Server terminated successfully (0). Closing log file.
```

**Comment by paperbenni** [comment]
Try pressing super + a and typing in tv
Does that also freeze stuff?

**Comment by mybigman** [comment]
Under iOS it resized the window but became super laggy.

**Comment by paperbenni** [comment]
Which hypervisor are you using

**Comment by mybigman** [comment]
virtualbox

**Comment by paperbenni** [comment]
What graphics are you using? Do you have 3d accelleration enabled?
Do you have ```xf86-video-vmware``` installed?

**Comment by mybigman** [comment]
I am using VMSVGA and ```xf86-video-vmware``` is installed. 3D accel is off as it tends to cause problems for some reason.

**Comment by paperbenni** [comment]
I recently fixed a resize related crash, it possibly could be a fix for this issue
