### ISSUE TITLE
small window size when moving window to larger display

### ISSUE THREAD

**Issue by con-f-use** [instantOS/instantWM#60]
After moving a window from a display with smaller resolution to one with a larger resolution that has at least one window (e.g. with <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>.</kbd>), those on the target display have the smaller's original window size. See picture of the larger display below:

![smaller](https://user-images.githubusercontent.com/11145016/101748974-788ac880-3acd-11eb-8183-e4deac533eea.png)

Triggering a refresh, e.g. by changing tags or opening another window on that display will cause everything to have the correct size. This is in tiling layout, but grid and possibly others have the same problem.

**Comment by con-f-use** [comment]
Also happens, when I click on a link on the smaller monitor and it is opened in a browser on the larger.

**Comment by con-f-use** [comment]
@paperbenni ... :grin:  ...

**Comment by paperbenni** [comment]
cool, github auto closes this stuff. 
Didn't mean to do that but I'm fairly certain it's fixed now
