### ISSUE TITLE
Top overlay ignores the bar getting toggled

### ISSUE THREAD

**Issue by bob8677** [instantOS/instantWM#61]
![20201212101906](https://user-images.githubusercontent.com/68208828/101989071-cb16e100-3c95-11eb-904c-7ffa3054c439.png)
![20201212101922](https://user-images.githubusercontent.com/68208828/101989076-d1a55880-3c95-11eb-8ef8-c6cc4a6aaa52.png)

**Comment by paperbenni** [comment]
Should be fixed with 37ec4628fd52913e7c57916519c7a255e6b632bd

**Comment by con-f-use** [comment]
@bob8677, please confirm and this issue will be closed.

**Comment by bob8677** [comment]
I can confirm that this fix works.
