### ISSUE TITLE
Cannot exit installer at partition select

### ISSUE THREAD

**Issue by ppenguin** [instantOS/instantWM#62]
I am installing over a Manjaro install with LVM on LUKS. Since this is not (yet) supported in the installer, (latest) at the point where I have to choose the root partition I need to open another terminal to decrypt the LUKS device, before being able to see it listed as a target partition. 

I seem to have no way to remove focus from the partition choice dialog not even `Ctrl-C` works. The only way appears to be enter a real terminal outside of X and do what I need to do (install cryptsetup and decrypt block device).

**Comment by con-f-use** [comment]
Benni is currently giving the installer a major rework. I'd be surprised if the issue is still there in beta 6. Feel free to re-open, if.

**Comment by ppenguin** [comment]
@con-f-use Now that's what I call a fast reply :smiley: 
Just for my current attempt: am I going to succeed installing by preparing decrypt manually, killing and rerunning the installer, or will I have many more issues because of this down the line? (I decided to go all-in with the beta on my laptop as my daily driver, call me crazy :wink: )

**Comment by con-f-use** [comment]
I can't guarantee anything, but if the install succeeds and the system boots, then there shouldn't be any other problems.

**Comment by paperbenni** [comment]
The repo for the installer is https://github.com/instantOS/instantARCH
Not a big deal, we're not swamped with issues here but just keep this in mind when anything else comes up :)
Btw, couldn't you just decrypt the device prior to starting the installation?
